"""add tables

Revision ID: 4d771cb7644e
Revises: 7387826afee5
Create Date: 2025-12-18 14:11:21.997602

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d771cb7644e"
down_revision: Union[str, Sequence[str], None] = "7387826afee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "category_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "category_id <> parent_category_id",
            name=op.f("ck_categories_ch_categories_parent_category_id"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["categories.category_id"],
            name=op.f("fk_categories_parent_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("category_id", name=op.f("pk_categories")),
    )
    op.create_index(
        op.f("ix_categories_parent_category_id"),
        "categories",
        ["parent_category_id"],
        unique=False,
    )
    op.create_table(
        "seller_profiles",
        sa.Column(
            "seller_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("store_name", sa.String(length=255), nullable=False),
        sa.Column("store_logs", sa.String(length=255), nullable=True),
        sa.Column("contact_info", sa.Text(), nullable=True),
        sa.Column("return_policy", sa.Text(), nullable=True),
        sa.Column("delivery_terms", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "store_name <> ''",
            name=op.f("ck_seller_profiles_ch_seller_profiles_store_name"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_seller_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("seller_id", name=op.f("pk_seller_profiles")),
        sa.UniqueConstraint("user_id", name="uq_seller_profiles_user_id"),
        sa.UniqueConstraint(
            "user_id", name=op.f("uq_seller_profiles_user_id")
        ),
    )
    op.create_table(
        "products",
        sa.Column(
            "product_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "name <> ''", name=op.f("ck_products_ch_products_name")
        ),
        sa.CheckConstraint(
            "discount BETWEEN 0 AND 100",
            name=op.f("ck_products_ch_products_discount"),
        ),
        sa.CheckConstraint(
            "price >= 0", name=op.f("ck_products_ch_products_price")
        ),
        sa.CheckConstraint(
            "stock_quantity >= 0",
            name=op.f("ck_products_ch_products_stock_quantity"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["seller_profiles.seller_id"],
            name=op.f("fk_products_owner_id_seller_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_products")),
    )
    op.create_index(
        op.f("ix_products_category_id"),
        "products",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_name"), "products", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_products_owner_id"), "products", ["owner_id"], unique=False
    )
    op.create_table(
        "ratings",
        sa.Column(
            "rating_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value BETWEEN 1 AND 5", name=op.f("ck_ratings_ch_ratings_value")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
            name=op.f("fk_ratings_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_ratings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("rating_id", name=op.f("pk_ratings")),
    )
    op.create_index(
        op.f("ix_ratings_product_id"), "ratings", ["product_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column(
            "review_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.user_id"],
            name=op.f("fk_reviews_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
            name=op.f("fk_reviews_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_reviews")),
    )
    op.create_index(
        op.f("ix_reviews_product_id"), "reviews", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_product_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_ratings_product_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_products_owner_id"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_table("seller_profiles")
    op.drop_index(
        op.f("ix_categories_parent_category_id"), table_name="categories"
    )
    op.drop_table("categories")
    # ### end Alembic commands ###
